
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: docker build -t karinapapa/fastzero:latest .

      - name: Push Docker Image
        run: docker push karinapapa/fastzero:latest

  
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: code checkout
        with:
          fetch-depth: 0  

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  trivy:
    name: Build Trivy
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Pull Docker Image
        run: docker pull karinapapa/fastzero:latest
 
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: karinapapa/fastzero
          format: 'sarif'
          output: 'trivy-results.sarif'
        
  helm-chart:
    name: Helm-Chart
    runs-on: ubuntu-latest  
    

    steps:
      - name: Clonar_repo
        uses: actions/checkout@v3
        with:
          repository: karinapapa/helm-repositorio 
          token: ${{ secrets.ACCESS_TOKEN_OPS }}
          path: api  

      - name: Verificar diretórios
        run: |
          ls -R api


      - name: Atualizar tag 
        run: |
          cd .api/fastapi
          pwd
          ls -a 
          sed -i 's|image:.*|image: '${{ steps.meta.outputs.tags }}'|' values.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_OPS }}

      - name: Commit e Push
        run: |
          cd api/fastapi
          pwd
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update docker tag para:  ${{ steps.meta.outputs.tags }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_OPS }}    



    
